esphome:
  name: "shahar-ai"
  friendly_name: "עוזר קולי שחר"

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

api:
ota:
  - platform: esphome

wifi:
  networks:
    - ssid: "mmmm"
      password: "0545468640"

i2c:
  id: bus_a
  sda: GPIO10
  scl: GPIO8
  scan: true

display:
  - platform: ssd1306_i2c
    id: my_display
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(my_font), "Hello Shahar!");

font:
  - file: "gfonts://Roboto"
    id: my_font
    size: 20

# הגדרות אודיו (נשאיר אותן כדי שלא יתנגשו)
i2s_audio:
  i2s_lrclk_pin: GPIO3
  i2s_bclk_pin: GPIO2

microphone:
  - platform: i2s_audio
    id: board_mic
    i2s_din_pin: GPIO4
    adc_type: external
    pdm: false
