esphome:
  name: "shahar-ai"

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

# הגדרת לוגר ל-UART כדי לראות משהו ב-USB
logger:
  hardware_uart: UART0
  level: DEBUG

wifi:
  networks:
    - ssid: "mmmm"
      password: "0545468640"
