name: Build ESPHome

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome

      - name: Build Binary
        run: esphome compile shahar-ai.yaml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .esphome/build/shahar-ai/.pioenvs/shahar-ai/firmware.bin
