name: Build ESPHome

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ESPHome Binary
        uses: esphome/build-action@v2
        id: esphome-build
        with:
          yaml_file: shahar-ai.yaml
          version: latest

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .esphome/build/shahar-ai/.pioenvs/shahar-ai/firmware.bin
