name: Build ESPHome

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install esphome esptool
      - run: esphome compile shahar-ai.yaml
      - name: Create Merged Binary
        run: |
          # מוצא את קובץ ה-args בכל מקום שהוא נמצא בו
          FLASH_ARGS=$(find . -name "*flash*_args" | head -n 1)
          echo "Found args file at: $FLASH_ARGS"
          
          # עובר לתיקייה שבה נמצא הקובץ כדי שהנתיבים היחסיים בתוכו יעבדו
          WORKDIR=$(dirname $FLASH_ARGS)
          FILENAME=$(basename $FLASH_ARGS)
          
          cd $WORKDIR
          python -m esptool --chip esp32c3 merge-bin -o ../../../merged_shahar.bin @$FILENAME

      - uses: actions/upload-artifact@v4
        with:
          name: full-firmware
          path: merged_shahar.bin
